name: Parse String
on:
  workflow_dispatch:
    inputs:
      value:
        description: 'From branch'
        required: true

jobs:
  parse-input:
    runs-on: ubuntu-latest
    name: Parsing input value
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Parse inputs
        id: parse
        uses: ./
        with:
          value: ${{ github.event.inputs.value }}
          run-all-default-values: 'run,all,ko,example'
      
      - name: Print parsed value
        run: echo "Parsed value is ${{ steps.parse.outputs.parsed }}"
    outputs:
      parsed: ${{ steps.parse.outputs.parsed }}
      is-empty: ${{ steps.parse.outputs.is-empty }}

  matrix-example:
    needs: parse-input
    if : ${{ needs.parse-input.outputs.is-empty == 'false' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        input: ${{ fromJson(needs.parse-input.outputs.parsed) }}
    name: Matrix example

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Print value
        run: echo "Value is ${{ matrix.input }}"
        
