name: Parse String
on:
  workflow_dispatch:
    inputs:
      value:
        description: 'From branch'
        required: true

jobs:
  parse-input:
    runs-on: ubuntu-latest
    name: Parsing input value
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse inputs
        id: parse
        uses: ./
        with:
          value: ${{ github.event.inputs.value }}
      
      - name: Print parsed value
        run: echo "Parsed value is ${{ steps.parse.outputs.parsed }}"
        
